name: Build Reusable workflow

on:
  workflow_call:
    outputs:
      artifact-version:
        description: "Artifact version"
        value: ${{ jobs.stage.outputs.artifact-version }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest

    outputs:
      artifact-version: ${{ steps.export-version.outputs.artifact-version }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Generate version
        run: |
          echo ARTIFACT_VERSION="${GITHUB_SHA}-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: Export version
        id: export-version
        run: |
          echo "::set-output name=artifact-version::$ARTIFACT_VERSION"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/**/*.xml'
          check_name: 'Test Results'

      - name: Publish test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: '**/build/reports/tests/**/*'
