name: Build

on:
  workflow_call:
    outputs:
      build-version:
        description: "The first output string"
        value: ${{ jobs.stage.outputs.build-version }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest

    outputs:
      build-version: ${{ steps.build-version.outputs.build-version }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Generate version
        run: |
          echo BUILD_VERSION="${GITHUB_SHA}-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: Remember unique build number
        id: build-version
        run: |
          echo "::set-output name=build-version::$BUILD_VERSION"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/**/*.xml'
          check_name: 'Test Results'

      - name: Publish test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: '**/build/reports/tests/**/*'
