name: Build

on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  workflow:
    runs-on: ubuntu-latest

    outputs:
      build: '**/build/**'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Generate unique build number
        run: |
          echo UNIQUE_BUILD_NUMBER="${GITHUB_SHA}-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: Display
        run: |
          echo "Number: $UNIQUE_BUILD_NUMBER"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon

      - name: Cache Build Output
        id: cache-build-output
        uses: actions/cache@v3
        with:
          path: '~/**/build/**/*'
          key: build-output-${{ github.run_id }}-${{ github.run_attempt }}
  workflow2:
    runs-on: ubuntu-latest
    needs: workflow

    steps:
      - name: Restore Build Output
        id: restore-build-output
        uses: actions/cache@v3
        with:
          path: '~'
          key: build-output-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/**/*.xml'
          check_name: 'Test Results'

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: '**/build/reports/tests/**/*'
