name: Feature Branch Workflow

on:
  push:
    branches-ignore: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

  static-analysis:
    uses: ./.github/workflows/reusable-static-analysis.yml

  print-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.artifact-version }}
