name: Default Branch Workflow

on:
  push:
    branches-ignore: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  print:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.build-version }}
