name: Master Branch Workflow

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  master:
    uses: ./.github/workflows/build.yml
